jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js 16 or later
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint '**/*.html'

      - name: Run Stylelint
        run: npx stylelint '**/*.css'
